### ISSUE TITLE
Remove duplicate types: Poly and Polygon

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geojson#10]
Both represent a Polygon. Poly was added in #8.

**Comment by calvinmetcalf** [comment]
the idea was poly represents a collection of rings (and wholes) while polygon represented the geometry type,

A better way forward might be to unify the multi and non multi types so there is only one type of polyone/point/linestrings that serialize to different types

**Comment by frewsxcv** [comment]
> A better way forward might be to unify the multi and non multi types so there is only one type of polyone/point/linestrings that serialize to different types

Can you expand on this idea? I don't completely understand and am curious what you mean

**Comment by calvinmetcalf** [comment]
points re just always have a vector of positions then when calling to json
on them based on the length of the vector we choose whether it is
 multipoint or point.  This is how shapefiles work (only for line strings
and polygons they have seperat points and multipoints)

**Comment by frewsxcv** [comment]
While you bring up interesting ideas about how to creatively model GeoJSON, I think it might be better for this library to stay as close to the [GeoJSON specification](http://geojson.org/geojson-spec.html) as possible and try not to introduce too many new ideas.

**Comment by calvinmetcalf** [comment]
One thing that would help discussions like this would be to come up with an internal geo.rs format that all the parsers can target.

**Comment by frewsxcv** [comment]
That's one of my goals with https://github.com/georust/rust-geo . And then for each reader/writer (GeoJSON/WKT/Shapefile/etc) there would be a `to_geo` and `from_geo` method on each type. If you have ideas on how to model the structs in rust-geo, feel free to open an issue/pull request
