### ISSUE TITLE
Parse TopoJSON

### ISSUE THREAD

**Issue by mgax** [georust/rust-geojson#14]
The [TopoJSON specification](https://github.com/topojson/topojson-specification/blob/master/README.md) is a useful guide.

**Comment by calvinmetcalf** [comment]
this might belong in it's own repo especially if you want to produce TopoJSON

**Comment by mgax** [comment]
The parsing is more involved than I expected. I created a separate repository: https://github.com/georust/rust-topojson.

**Comment by frewsxcv** [comment]
Thanks @mgax , sounds good. Maybe if we expose enough of the `rust-geojson` internals we could reuse them in `rust-topojson`.

**Comment by mgax** [comment]
Well, the parser is transforming the Json it receives, producing a valid GeoJSON, and then calls rust-geojson to parse that, so we're reusing already.
