### ISSUE TITLE
Published as rust-graph on crates.io

### ISSUE THREAD

**Issue by gsingh93** [georust/rust-geojson#28]
Shouldn't this be published as rust-geojson on crates.io, not rust-graph: https://crates.io/crates/rust-graph

**Comment by gsingh93** [comment]
Oh, it looks like it's published as both. I think you should remove the rust-graph package if possible, otherwise contact the crates.io maintainers to remove it. It's a name that really should be reserved for an actual graph library.

**Comment by skj3gg** [comment]
Just looks like @frewsxc used the rust-geojson .toml as a base and forgot to change the repository.

**Comment by frewsxcv** [comment]
On vacation currently. I'll address this when I get back

**Comment by frewsxcv** [comment]
Yes, I accidentally published `rust-graph` with the `rust-geojson` project file

@gsingh93 I noticed you have a project called `rust-graph`, do you want it on crates.io? I no longer need it

**Comment by gsingh93** [comment]
I renamed my crate to `rust_graph` published that on crates.io, which I'm ok with. Thanks for the offer though.

**Comment by gsingh93** [comment]
@frewsxcv I received an email from @alexcrichton saying they don't low crates that differ by only a hyphen/underscore on crates.io, and that I should rename my crate to something else. Since my graph package is an actual graph package, could you rename or remove your crate?

**Comment by frewsxcv** [comment]
@gsingh93 You can remove crates, but I'll add you as an admin to the rust_graph crate

**Comment by frewsxcv** [comment]
done

**Comment by frewsxcv** [comment]
feel free to remove me as an admin if you want complete domination

**Comment by alexcrichton** [comment]
@gsingh93 oh if you're the owner of both crates, which would you prefer to have? (I don't mind deleting either). Thanks @frewsxcv for helping out!

**Comment by gsingh93** [comment]
@alexcrichton I think rust-graph is the more common convention so I guess I'll take that one. You can delete rust_graph (can package owners do this? I couldn't figure out how). And to either of you, how does one change the owners/admins of a package?

**Comment by frewsxcv** [comment]
`cargo owner --help`

**Comment by alexcrichton** [comment]
No I have to manually delete the crate (I'll take care of that). Thanks for the quick response!
