### ISSUE TITLE
Better handling for CRS: it can exist, be null, or not exist

### ISSUE THREAD

**Issue by frewsxcv** [georust/rust-geojson#34]
For example, notice the CRS property in each of the following GeoJSON examplse:

``` json
{
 "coordinates": [1.0, 2.0],
 "type": "Point",
}
```

``` json
{
 "coordinates": [1.0, 2.0],
 "type": "Point",
 "crs": null,
}
```

``` json
{
 "coordinates": [1.0, 2.0],
 "type": "Point",
 "crs": {
  "type": "name",
  "properties": {
   "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
  }
 }
}
```

Right now, for all core GeoJSON types, the `crs` property is either `Some` (if it exists on an object) or `None` (if it does _not_ exist on an object). There is currently no way to represent it as `null`.

Options:
1. We could make it an `Option<Option<Crs>>` (the outer `Option` indicates if the key exists, the inner `Option` indicates if the value is null)
2. Create a new generic type that handles all three cases:
   
   ``` rust
   pub enum OptionNull<T> {
       Some(T),
       Null,
       None,
   }
   ```
3. Add a new enum variant `Null` on `Crs` that would indicate null. e.g.:
   
   ``` rust
   pub enum Crs {
       Null,
   
       Named {
           name: String,
       },
   
       Linked {
           href: String,
           type_: Option<String>,
       },
   }
   ```

**Comment by mgax** [comment]
Or we could just fold `crs: null` and missing `crs` to the same value, esentially ignoring `crs: null`.

**Comment by frewsxcv** [comment]
As of RFC 7946, the "crs" member has been removed.

https://github.com/georust/rust-geojson/issues/53
