### ISSUE TITLE
Clean up bottom of LICENSE

### ISSUE THREAD

**Issue by skj3gg** [georust/rust-geojson#4]
This Apache License not properly filled out.

Brings to question, is copyright `Cory Farwell` or `GeoRust`

**Comment by frewsxcv** [comment]
The bottom section of the Apache license [is meant to tell you what to add to the header of each source file](https://github.com/georust/rust-geojson/blob/9a8616655c12367b5b89f2b6f1dccdfb5e3922f1/LICENSE#L178-L187), so it's supposed to be not filled out, so all Apache license files should have the same contents ([unlike BSD](https://github.com/frewsxcv/python-geojson/commit/cfa28c0f278c3e13ed72866fd3604e8bfddeb1fc)). That said, we still need to add that header to all the source files ([here's](https://github.com/rust-lang/rustc-serialize/blob/e8a3aeac8ea793c0875a003fe3a5a3e2927d99bc/src/json.rs#L1-L9) an example). Similarly to rust-lang's attribution, we can just attribute it to `The GeoRust Developers`.

**Comment by skj3gg** [comment]
Opps, I guess I've been doing it wrong, never included the instructions to how to apply it when committing a license.
