### ISSUE TITLE
Nullable Feature geometry

### ISSUE THREAD

**Issue by jfirebaugh** [georust/rust-geojson#42]
According to the [GeoJSON specification](http://geojson.org/geojson-spec.html#feature-objects), the `"geometry"` property of a Feature can be a JSON null value. I noticed that in other respects, nullability is reflected in the Rust API via `Option`, but this doesn't seem to be the case for the `geometry` field of `geojson::Feature`. Is this intentional?

**Comment by frewsxcv** [comment]
You are right, this was an oversight. I can make this change later today and release a new major version since this is a breaking change. Thanks for pointing this out!

**Comment by frewsxcv** [comment]
Version 0.3.0 has been published that includes the fix for this. Thanks again for filing this issue! 🎊
