### ISSUE TITLE
Docs out of date w.r.t. serde?

### ISSUE THREAD

**Issue by rory** [georust/rust-geojson#78]
Docs ( https://georust.github.io/rust-geojson/geojson/index.html )  imply that serde is an optional alternative, but it looks like it only uses serde?

**Comment by frewsxcv** [comment]
There used to be an option to select between rustc-serialize and serde, but recently we changed it to just use serde. So looks like the docs need to be updated

**Comment by frewsxcv** [comment]
https://github.com/georust/rust-geojson/pull/60

**Comment by KodrAus** [comment]
Whoops, must've missed that. I'll go update the docs today.

**Comment by KodrAus** [comment]
I think the docs on github.io are just out of date. @frewsxcv do you think we still need these now that we've got docs.rs?

**Comment by frewsxcv** [comment]
Nah, we can just used docs.rs and get rid of our own infra 👍

**Comment by frewsxcv** [comment]
Fixed in https://github.com/georust/rust-geojson/pull/79
