### ISSUE TITLE
Create method to read `GeoJson()` as object

### ISSUE THREAD

**Issue by madeindjs** [georust/rust-geojson#84]
I want to read a simply GeoJson file. So I create a script like this

~~~rust
let mut f = File::open("lyon-subway.geo.json").expect("file not found");

let mut geojson_str = String::new();
f.read_to_string(&mut geojson_str).expect("something went wrong reading the file");

let geojson: GeoJson = geojson_str.parse::<GeoJson>().unwrap();
println!("{:?}", geojson);
~~~

Now I wan't to use `geojson` as object (iterates on `Feature` object by example) but I don't find any way to do this.. 

~~~rust
for feature in geojson.features {
    println!("{:?}", feature.properties);;
}
~~~

Is existing a way to do this? Is it possible to implement it?

**Comment by urschrei** [comment]
You have to match on your `geojson` enum. Something like:


    match &geojson {
        &GeoJson::FeatureCollection(ref fc) => {
            for feature in &fc.features {
                match &feature.geometry {
                    &Some(ref geometry) => match geometry.value {
                        Value::Polygon(_) => { println!("Polygon: {:?}", geometry.value); },
                        Value::MultiPolygon(_) => { println!("MultiPolygon: {:?}", geometry.value); },
                        // other geometries go here
                        _ => println!("Other geometry")
                    },
                    _ => println!("No feature could be processed")
                }
            }
        },
        // you can also match on GeoJson::Feature and GeoJson::Geometry, then sub-match as above
        _ => println!("Found a Feature or a Geometry")
    };

**Comment by madeindjs** [comment]
Thank you a lot for your answer!
